config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:show, :edit, :update] do
    resource :relationship, only: [:create, :destroy]
    member do
      get '/dreams', to: 'profiles#dreams'
    end
  end

  resources :dreams do
    member do
      put '/realized', to: 'dreams#realized'
    end
    resources :kitties, only: [:show, :new, :create]
    resource :like, only: [:create, :destroy]
  end

  resources :kitties, only: [] do
    put '/reveal', to: 'kitties#reveal'
    resources :contributors, only: [:new, :create]
  end

  resources :contributors, only: [] do
    resources :payments, only: [:new, :create]
  end

  resources :notifications, only: [:show]

  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: :registrations }

  root to: 'pages#home'
end

app/views/shared/_buttons_cat.html.erb
<% categories.each do |category| %>
  <%= link_to category, "#", class: "btn-dreamlist-2 text-center js-btn-category active", "data-category" => category %>
<% end %>

app/views/shared/_dream_card.html.erb
<div class="col-xs-12 col-sm-4">
  <% if dream.kitty.present? %>
  <div class="dream-card <%= dream.category %>">
    <%= link_to '', dream_path(dream), class: 'card-link' %>
    <div class="dream-picture" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.2) 50%), url('<%= dream_picture_path(dream) %>');">
      <div class="like-actions" data-id="<%= dream.id %>">
        <%= like_action_for(dream) %>
      </div>
      <% if dream.reached == false %>
        <%= link_to "Contribute", dream_path(dream), class: 'contribute' %>
      <% end %>
      <%= user_avatar_tag dream.user, class: 'avatar' %>
      <div class="avatar"></div>
    </div>
    <div class="dream-text">
      <h4><%= dream.title %></h4>
      <% if !(dream.kitty.goal_amount.to_i == 0 && dream.kitty.total_contribution_public.to_i == 0) || dream.kitty.secret? %>
        <div class="global-bar">
          <div class="participation-bar" style="width: <%= number_to_percentage(dream.kitty.contribution_avancement_public); %>"></div><% if current_user != dream.user %><div class="participation-bar-private" style="width: <%= number_to_percentage(dream.kitty.contribution_avancement_private); %>"></div><% end %>
        </div>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
 <div class="alert alert-info alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
   <%= notice %>
 </div>
<% end %>
<% if alert %>
 <div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
   <%= alert %>
 </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer hidden-xs hidden-sm">
  <div class="container">

    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <ul class="list-inline">
          <li>
            <i class="fa fa-facebook" aria-hidden="true"></i>
          </li>
          <li>
            <i class="fa fa-twitter" aria-hidden="true"></i>
          </li>
          <li>
            <i class="fa fa-youtube" aria-hidden="true"></i>
          </li>
          <li>
            <i class="fa fa-instagram" aria-hidden="true"></i>
          </li>
        </ul>
      </div>

      <div class="col-xs-12 col-sm-6">
        <div class="text-footer-right">
          <p>Coded with love @ LeWagon</p>
        </div>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? %>

  <div class="footer mobile hidden-md hidden-lg">
    <form action="/dreams" method="get">
      <div class="search">
        <%= image_tag "search.png", class: "search-icon" %>
        <input type="text" name="query" class="search-input" placeholder="Search for a dream...">
        <button type="submit" class="navbar-wagon-search-btn"></button>
      </div>
    </form>

    <div class="dropup">
      <%= content_tag "div", class: "dropdown-toggle navbar-wagon-item navbar-wagon-link navbar-alarm", "data-toggle" => "dropdown" do %>
        <div class="badge-container">
          <%= image_tag "alarm.png", class: "alarm" %>
          <% if current_user.notifications.where(read: false).count > 0 %>
            <div class="badge badge-blue"><%= current_user.notifications.where(read: false).count %></div>
          <% end %>
        </div>
      <% end %>
      <% if current_user.notifications.count > 0 %>
        <ul class="alarm-ul dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% current_user.notifications.ordered.limit(4).reverse.each do |notification| %>
            <li class="notif-<%= notification.read ? 'read' : 'unread' %>">
              <%= link_to notification_path(notification) do %>
                <%= notification.content.html_safe %>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-dreamlist navbar-dreamlist-fixed">

  <div class="navbar-wagon-left hidden-xs hidden-sm">
    <div class="navbar-wagon-item">
      <div class="explore">
        <div class="dropdown">
          <%= link_to 'Explore', '', class: 'dropdown-toggle navbar-wagon-item navbar-dreamlist-button', "data-toggle" => "dropdown"  %>
          <ul class="dropdown-menu navbar-dreamlist-dropdown-explore left">
            <% Dream::CATEGORIES.each do |category| %>
              <li>
                <%= link_to dreams_path(category: category) do %>
                  <%= t(".profile", default: category) %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="navbar-wagon-item">
      <!-- button to create a dream -->
      <%= link_to t(".top_call_to_action", default: "Create a dream"), new_dream_path, class: "navbar-wagon-item navbar-dreamlist-button" %>
    </div>
  </div>

  <!-- Logo -->
  <div class="navbar-middle">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo-dreamlist-text1.png" %>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Search form -->
      <form action="/dreams" method="get">
        <div class="search">
          <%= image_tag "search.png", class: "search-icon" %>
          <input type="text" name="query" class="search-input" placeholder="Search for a dream...">
          <button type="submit" class="navbar-wagon-search-btn"></button>
        </div>
      </form>

      <!-- Notification -->
      <div class="dropdown">
        <%= content_tag "div", class: "dropdown-toggle navbar-wagon-item navbar-wagon-link navbar-alarm", "data-toggle" => "dropdown" do %>
          <div class="badge-container">
            <%= image_tag "alarm.png", class: "alarm" %>
            <% if current_user.notifications.where(read: false).count > 0 %>
              <div class="badge badge-blue"><%= current_user.notifications.where(read: false).count %></div>
            <% end %>
          </div>
        <% end %>
        <% if current_user.notifications.count > 0 %>
          <ul class="alarm-ul dropdown-menu dropdown-menu-right navbar-dreamlist-dropdown-notif">
            <% current_user.notifications.ordered.limit(25).each do |notification| %>
              <li class="notif-<%= notification.read ? 'read' : 'unread' %>">
                <%= link_to notification_path(notification) do %>
                  <%= notification.content.html_safe %>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= user_avatar_tag current_user, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li class="">
              <%= link_to dreams_profile_path(current_user) do %>
                <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li class="">
              <%= link_to profile_path(current_user) do %>
                <%= t(".profile", default: "Settings") %>
              <% end %>
            </li>
            <li class="">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Sign out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-dreamlist-button" %>
      <%= link_to t(".sign_in", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-dreamlist-button" %>

       <!-- Search form -->
      <form action="/dreams" method="get">
        <div class="search">
          <%= image_tag "search.png", class: "search-icon" %>
          <input type="text" name="query" class="search-input" placeholder="Search for a dream...">
          <button type="submit" class="navbar-wagon-search-btn"></button>
        </div>
      </form>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <% if user_signed_in? %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile", dreams_profile_path(current_user) %></li>
          <li><%= link_to "Create a dream", new_dream_path %></li>
          <li><%= link_to "Settings", profile_path(current_user) %></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to t(".sign_in", default: "Sign in"), new_user_session_path %></li>
          <li><%= link_to t(".sign_in", default: "Sign up"), new_user_registration_path %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar_settings.html.erb
<div class="navbar_settings">
  <div class="container">
    <% if user_signed_in? %>
      <div class="dreams-menu hidden-xs hidden-sm">
        <div class="navbar-right-links text-center">
          <div class="tabs-settings">
            <%= link_to 'Account', '#', class: "navbar-dreamlist-button text-center tab-settings active", "data-target" => "#tab-account" %>
            <%= link_to 'Your Contributions', '#', class: "navbar-dreamlist-button text-center tab-settings", "data-target" => "#tab-contributions" %>
            <%= link_to 'Messages', '#', class: " navbar-dreamlist-button text-center tab-settings", "data-target" => "#tab-messages" %>
            <%= link_to 'Money Pots', '#', class: " navbar-dreamlist-button text-center tab-settings", "data-target" => "#tab-money" %>
          </div>

        </div>
      </div>
      <div class="dreams-menu mobile hidden-md hidden-lg">
        <div class="navbar-left-links text-center">
          <div class="tabs-settings">
            <div class="dropdown">
              <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to 'Account', '#', "data-target" => "#tab-account", class: 'tab-settings' %></li>
                <li><%= link_to 'Your contributions', '#', "data-target" => "#tab-contributions", class: 'tab-settings' %></li>
                <li><%= link_to 'Messages', '#', "data-target" => "#tab-messages", class: 'tab-settings' %></li>
                <li><%= link_to 'Money Pots', '#', "data-target" => "#tab-money", class: 'tab-settings' %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_profile_show.html.erb
<div class="profile-information">
  <div class="row">
    <div class="col-xs-6 col-sm-8">
      <div class="user-description">
        <h2><%= user.first_name.capitalize %> <%= user.last_name.capitalize %></h2>
        <div class="text-inline">
          <p class="nb-follower"><%= user.followers.count %> followers  — </p>
          <p class="nb-following"><%= user.following.count %> following </p>
        </div>
        <div class="edit-link">
          <% if current_user != user %>
            <div class="follow-actions" data-id="<%= user.id %>">
              <%= follow_action_for(user) %>
            </div>
          <% end %>
        </div>
        <% if user == current_user %>
          <br>
          <br>
          <%= link_to "Create a dream", new_dream_path, class: "btn-dreamlist" %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-6 col-sm-4 text-center">
      <%= user_avatar_tag user, class: 'avatar-large user-avatar' %>
    </div>
    <div class="col-xs-12">
      <br>
      <br>
      <br>

      <div class="dreams-menu hidden-xs hidden-sm">
        <div class="navbar-right-links text-center">
          <div class="tabs">
            <%= link_to 'Dreams', '#', class: "navbar-dreamlist-button text-center tab", "data-target" => "#tab-user-dreams-in-cat" %>
            <%= link_to 'Dreams liked', '#', class: "navbar-dreamlist-button text-center tab", "data-target" => "#tab-loved-dreams" %>
            <%= link_to 'Following', '#', class: " navbar-dreamlist-button text-center tab", "data-target" => "#tab-followed-users" %>
            <%= link_to 'Followers', '#', class: " navbar-dreamlist-button text-center tab", "data-target" => "#tab-followers" %>
            <%= link_to "Following's dreams", '#', class: " navbar-dreamlist-button text-center tab", "data-target" => "#tab-followed-dreams" %>
            <%= link_to "Realized dreams", '#', class: " navbar-dreamlist-button text-center tab", "data-target" => "#tab-realized-dreams" %>
          </div>
        </div>
      </div>
      <div class="dreams-menu mobile hidden-md hidden-lg">
        <div class="navbar-left-links text-center mobile">
          <div class="tabs-name">
            <%= link_to 'Dreams', '#', class: "navbar-dreamlist-button text-center tab-name active", "data-target" => "#tab-user-dreams-in-cat" %>
            <%= link_to 'Dreams liked', '#', class: "navbar-dreamlist-button text-center tab-name hidden", "data-target" => "#tab-loved-dreams" %>
            <%= link_to 'Following', '#', class: " navbar-dreamlist-button text-center tab-name hidden", "data-target" => "#tab-followed-users" %>
            <%= link_to 'Followers', '#', class: " navbar-dreamlist-button text-center tab-name hidden", "data-target" => "#tab-followers" %>
            <%= link_to "Following's dreams", '#', class: " navbar-dreamlist-button text-center tab-name hidden", "data-target" => "#tab-followed-dreams" %>
            <%= link_to "Realized dreams", '#', class: " navbar-dreamlist-button text-center tab-name hidden", "data-target" => "#tab-realized-dreams" %>
          </div>
          <div class="tabs">
            <div class="dropdown">
              <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to 'Dreams', '#', "data-target" => "#tab-user-dreams-in-cat", class: 'tab' %></li>
                <li><%= link_to 'Dreams liked', '#', "data-target" => "#tab-loved-dreams", class: 'tab' %></li>
                <li><%= link_to 'Following', '#', "data-target" => "#tab-followed-users", class: 'tab' %></li>
                <li><%= link_to 'Followers', '#', "data-target" => "#tab-followers", class: 'tab' %></li>
                <li><%= link_to "Following's dreams", '#', "data-target" => "#tab-followed-dreams", class: 'tab' %></li>
                <li><%= link_to "Realized dreams", '#', "data-target" => "#tab-realized-dreams", class: 'tab' %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_show_dream_navbar.html.erb
<div class="navbar-show-dream">
    <div class="navbar-wagon-item">
    <h4><%= @dream.title %></h4>
    </div>
    <div class="show-navbar-btn-items">
    <div class="like-part">
      <div class="like-actions" data-id="<%=@dream.id%>">
        <%= like_action_for(@dream) %>
      </div>
    </div>
    <%= link_to "Support this dream", new_kitty_contributor_path(@dream.kitty), class: 'btn-dreamlist' %>
    </div>
</div>

app/views/shared/_tableau.html.erb
<div class="tableau">
  <%= link_to "", "#", class: "tableau-link" %>
  <div class="photos-dreams">
    <div class="row">
      <% if dreams.count >= 6 %>
        <% i = 1 %>
        <% 6.times do %>
          <div class="col-xs-4">
            <div class="dream-image" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.4)), url('<%= dream_picture_path(dreams[i], width: 100, height: 100, crop: :fill) %>');">
            </div>
          </div>
          <% i += 1 %>
        <% end %>
      <% else %>
        <% dreams.each do |dream| %>
          <div class="col-xs-4">
            <div class="dream-image" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.4)), url('<%= dream_picture_path(dream, width: 100, height: 100, crop: :fill) %>');">
            </div>
          </div>
        <% end %>
        <% (6 - dreams.count).times do %>
          <div class="col-xs-4">
            <div class="dream-image"></div>
          </div>
        <% end %>
      <% end %>

      <div class="col-xs-12">
        <p><%=category.capitalize%></p>
      </div>
    </div>
  </div>
</div>