config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:show, :edit, :update] do
    resource :relationship, only: [:create, :destroy]
    member do
      get '/dreams', to: 'profiles#dreams'
    end
  end

  resources :dreams do
    member do
      put '/realized', to: 'dreams#realized'
    end
    resources :kitties, only: [:show, :new, :create]
    resource :like, only: [:create, :destroy]
  end

  resources :kitties, only: [] do
    put '/reveal', to: 'kitties#reveal'
    resources :contributors, only: [:new, :create]
  end

  resources :contributors, only: [] do
    resources :payments, only: [:new, :create]
  end

  resources :notifications, only: [:show]

  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: :registrations }

  root to: 'pages#home'
end

app/views/shared/show_dream/_dream_no_amount_desc.html.erb
<!-- information about kitty evolution -->
<div class="row">
  <div class="col-xs-12 col-sm-6">
    <% if (current_user != dream.user) %>
      <div class="kitty-total-amount">
        <p> Money pot: </p>
        <p class="strong-black"><%= (dream.kitty.total_contribution_public + dream.kitty.total_contribution_private).to_i %> €</p>
      </div>
    <% else %>
      <div class="kitty-total-amount">
        <p> Money pot: </p>
        <p class="strong-black"><%= dream.kitty.total_contribution_public.to_i %> €</p>
      </div>
    <% end %>
  </div>

  <div class="col-xs-12 col-sm-6">
    <div class="revealing" data-id="<%=@dream.id%>">
      <% if (current_user != dream.user) && @dream.kitty.secret? %>
        <%= link_to 'Disclose secret contributions', kitty_reveal_path(@dream.kitty), method: :put, remote: true,
        data: { confirm: '',
          'text': 'Are you sure you want to reveal all the secret contributions?',
          'width': '400px',
          'customClass': 'modal',
          'confirm-button-text': 'Yes',
          'cancel-button-text': 'Cancel',
          'confirm-button-color': '#526889',
          'sweet-alert-type': 'info'}, class: 'btn-dreamlist-blue width_240 btn-reveal text-center' %>
      <% end %>
      <% if (current_user == dream.user) && @dream.reached == false %>
        <%= link_to 'Dream realized', realized_dream_path(@dream), method: :put, remote: true,
        data: { confirm: '',
          'text': 'Are you sure you realized this dream? If so, no one will be able to contribute anymore.',
          'width': '400px',
          'customClass': 'modal',
          'confirm-button-text': 'Yes',
          'cancel-button-text': 'Cancel',
          'confirm-button-color': '#526889',
          'sweet-alert-type': 'info'}, class: 'btn-dreamlist-blue width_240 btn-reveal text-center' %>
      <% end %>
    </div>
  </div>

</div>
<div class="row">
  <div class="kitty-no-goal-amount">
    <h5>There is no goal amount for this money pot. Feel free to contribute as much as you wish!</h5>
  </div>
</div>

<div class="two-columns">
  <div class="row">
  <div class="col-xs-12 col-sm-6">
    <div class="kitty-details">

    <% if @dream.kitty.private? %>
      <% if dream.kitty.total_contribution_public > 0 %>
        <h5 class="strong-green">You already saved <%= @dream.kitty.total_contribution_public.to_i %> € for your dream</h5>
      <% else %>
        <h5 class="strong-green text-center">There is no contribution for now</h5>
      <% end %>
    <% else %>
      <% if dream.kitty.total_contribution_public == 0 %>
        <h5 class="text-center">There is no public contribution for now. <span class="strong-green-small"><%= link_to "Be the first one!", new_kitty_contributor_path(dream.kitty) %></span></h5>
      <% else %>
        <h5>Public contributions</h5>
        <div class="metric-container">
          <div class="metric">
            <p class="strong-green"><%= @dream.kitty.total_contribution_public.to_i %> €</p>
            <p>collected</p>
          </div>
          <div class="metric">
            <% if !@dream.kitty.private? %>
              <p class="strong"><%= @dream.kitty.public_contributors_count %></p>
              <p>contributions</p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>

    <div class="col-xs-12 col-sm-6">
      <% if !(dream.kitty.total_contribution_private == 0 && dream.kitty.total_contribution_public == 0) %>
        <%= render 'shared/show_dream/kitty_infos_private_contribution', dream: @dream, user: @user %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/show_dream/_dream_with_amount_desc.html.erb
<!-- information about kitty evolution -->
<div class="row">
  <div class="col-xs-12 col-sm-6">
    <% if (current_user != dream.user) %>
      <div class="kitty-total-amount">
        <p> Money pot: </p>
        <p class="strong-black"><%= (dream.kitty.total_contribution_public + dream.kitty.total_contribution_private).to_i %> € / <%= dream.kitty.goal_amount.to_i %> €</p>
      </div>
      <% else %>
      <div class="kitty-total-amount">
        <p> Money pot: </p>
        <p class="strong-black"><%= dream.kitty.total_contribution_public.to_i %> € / <%= dream.kitty.goal_amount.to_i %> €</p>
      </div>
    <% end %>

    <!-- barre avancement kitty -->
    <div class="global-bar">
      <div class="participation-bar" style="width: <%= number_to_percentage(dream.kitty.contribution_avancement_public); %>"></div><% if current_user != dream.user %><div class="participation-bar-private" style="width: <%= number_to_percentage(dream.kitty.contribution_avancement_private); %>"></div><% end %>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6">
    <div class="revealing" data-id="<%=@dream.id%>">
      <% if (current_user != dream.user) && @dream.kitty.secret? %>
        <%= link_to 'Disclose secret contributions', kitty_reveal_path(@dream.kitty), method: :put, remote: true,
        data: { confirm: '',
          'text': 'Are you sure you want to reveal all the secret contributions?',
          'width': '400px',
          'customClass': 'modal',
          'confirm-button-text': 'Yes',
          'cancel-button-text': 'Cancel',
          'confirm-button-color': '#526889',
          'sweet-alert-type': 'info'}, class: 'btn-dreamlist-blue width_240 btn-reveal text-center' %>
      <% end %>
      <% if (current_user == dream.user) && @dream.reached == false %>
        <%= link_to 'Dream realized', realized_dream_path(@dream), method: :put, remote: true,
        data: { confirm: '',
          'text': 'Are you sure you realized this dream? If so, no one will be able to contribute anymore.',
          'width': '400px',
          'customClass': 'modal',
          'confirm-button-text': 'Yes',
          'cancel-button-text': 'Cancel',
          'confirm-button-color': '#526889',
          'sweet-alert-type': 'info'}, class: 'btn-dreamlist-blue width_240 btn-reveal text-center' %>
      <% end %>
    </div>
  </div>

</div>
  <!-- text information about kitty -->
  <div class="two-columns">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="kitty-details">
          <% if dream.kitty.total_contribution_public == 0 %>
            <h5>There is no public contribution for now. <span class="strong-green-small"><%= link_to "Be the first one!", new_kitty_contributor_path(dream.kitty) %></span></h5>
          <% else %>


            <h5>Public contributions</h5>

            <div class="metric-container">
              <div class="metric">
                <p class="strong-green"><%= dream.kitty.total_contribution_public.to_i %> €</p>
                <p>out of <%= dream.kitty.goal_amount.to_i %> €</p>
              </div>


              <div class="metric">
                <p class="strong"><%= number_to_percentage(dream.kitty.real_contribution_avancement, precision: 2) %></p>
                <p>collected</p>
              </div>


              <div class="metric">
                <p class="strong"><%= dream.kitty.public_contributors_count %></p>
                <p>contributions</p>
              </div>
            </div>

          <% end %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6">
        <% if !(dream.kitty.total_contribution_private == 0 && dream.kitty.total_contribution_public == 0) %>
          <%= render 'shared/show_dream/kitty_infos_private_contribution', dream: @dream, user: @user %>
        <% end %>
      </div>

      </div>


  </div>

app/views/shared/show_dream/_kitty_infos_private_contribution.html.erb
<div class="kitty-details private">
  <% if current_user != dream.user %>


    <% if dream.kitty.total_contribution_private == 0 && dream.kitty.total_contribution_public > 0 %>
      <h5 class="text-center">There is no secret contribution for now. <span class="strong-blue-small"><%= link_to "Be the first one!", new_kitty_contributor_path(dream.kitty) %></span></h5>
    <% else %>
      <h5>Secret contributions</h5>

      <div class="metric-container">
        <div class="metric">
          <p class="strong-blue"><%= dream.kitty.total_contribution_private.to_i %> €</p>
          <p>out of <%= dream.kitty.goal_amount.to_i %> €</p>
        </div>

        <% if dream.kitty.goal_amount.to_i > 0 %>
          <div class="metric">
            <p class="strong"><%= number_to_percentage(dream.kitty.real_contribution_avancement_private, precision: 2) %></p>
            <p>collected</p>
          </div>
        <% end %>

        <div class="metric">
          <p class="strong"><%= dream.kitty.contributors.count - dream.kitty.public_contributors_count %></p>
          <p>contributions</p>
        </div>

        </div>
    <% end %>



  <% end %>

</div>

app/views/shared/show_dream/_links_dream.html.erb
<div class="content-links text-center">

  <div class="share-part">
    <p id="shareBtn"><%= icon("facebook") %></p>
    <p id=""><%= icon("instagram")%></p>
    <p id=""><%= icon("pinterest")%></p>
  </div>

</div>

app/views/shared/show_dream/_navbar.html.erb
<div class="navbar-show-dream navbar-show-dream-sticky hidden-xs hidden-sm">
    <!-- avatar dream owner -->
    <div class="info-owner">
      <%= link_to dreams_profile_path(@dream.user) do %>
        <%= user_avatar_tag @dream.user, class: 'avatar-medium' %>
      <% end %>

      <div class="name-edit">
        <p><%= @dream.user.first_name %> <%= @dream.user.last_name %></p>
        <!-- edit or follow your dream -->
        <div class="edit-link">
          <% if current_user == @dream.user %>
            <%= link_to 'Edit', edit_dream_path(@dream), class: 'btn-dreamlist-default' %>
          <% else %>
            <div class="follow-actions" data-id="<%= @dream.user.id %>">
              <%= follow_action_for(@dream.user) %>
            </div>
          <% end %>
        </div>


      </div>
      <%= render 'shared/show_dream/links_dream', dream: @dream%>
    </div>


    <div class="show-navbar-btn-items">
      <div class="like-part">
        <div class="like-actions" data-id="<%=@dream.id%>">
          <%= like_action_for(@dream) %>
        </div>
      </div>
      <% if @dream.reached == false %>
        <% if current_user != @dream.user && @dream.kitty.private? %>
          <!-- <h5>kitty closed</h5> -->
        <% else %>
          <%= link_to "Support this dream", new_kitty_contributor_path(@dream.kitty), class: 'btn-dreamlist' %>
        <% end %>
      <% end %>
    </div>
</div>

<div class="navbar-show-dream navbar-show-dream-sticky mobile hidden-md hidden-lg">
      <div class="info-owner">
        <%= link_to dreams_profile_path(@dream.user) do %>
        <%= user_avatar_tag @dream.user, class: 'avatar-medium' %>
        <% end %>
      </div>

      <div class="show-navbar-btn-items">
      <div class="like-part">
        <div class="like-actions" data-id="<%=@dream.id%>">
          <%= like_action_for(@dream) %>
        </div>
      </div>
      <% if @dream.reached == false %>
        <% if current_user != @dream.user && @dream.kitty.private? %>
          <!-- <h5>kitty closed</h5> -->
        <% else %>
          <%= link_to "Support this dream", new_kitty_contributor_path(@dream.kitty), class: 'btn-dreamlist' %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/shared/show_dream/_participation_bar.html.erb
<% if dream.user %>
  <%= @dream.kitty.contribution_avancement_public %>
<% else %>
  <%=  %>
<% end %>

app/views/shared/show_dream/_under_navigation.html.erb
<div class="bg-color-white">
  <div class="container">
    <div class="dreams-menu hidden-xs hidden-sm">

      <div class="navbar-right-links text-center">
        <div class="tabs">
          <div class="navbar-right-links text-center buttons-links-tabs">

            <div class="navbar-dreamlist-button text-center tab", data-target="#tab-similar-dreams">
              <p>Similar dreams</p>
              <p class="nb">
                <% if dream.user.has_dream_in?(dream.category) %>
                  <% if dreams_in_category_except_this(dream, dream.category).count > 0 %>
                    <%= dreams_in_category_except_this(dream, dream.category).count %>
                  <% else %>
                    <%= '-' %>
                  <% end %>
                <% else %>
                  <%= '-' %>
                <% end %>
               </p>
            </div>

            <div class="navbar-dreamlist-button text-center tab", data-target="#tab-likers">
              <p>Popularity</p>
              <p class="nb"><%= dream.likes.count > 0 ? dream.likes.count : '-' %></p>
            </div>

            <div class="navbar-dreamlist-button text-center tab", data-target="#tab-contributors">
              <p>Contributors</p>
              <p class="nb"><%= dream.kitty.contributors.count > 0 ? dream.kitty.different_user_contributors.count : '-' %></p>
            </div>

          </div>
        </div>
      </div>

    </div>

    <div class="dreams-menu mobile hidden-md hidden-lg">
      <div class="navbar-wagon-item">
        <div class="navbar-right-links text-center">
          <div class="tabs">
            <div class="dropdown">
              <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li class="tab", data-target="#tab-similar-dreams">
                  <p>Similar dreams</p>
                </li>
                <li class="tab", data-target="#tab-likers">
                  <p>Popularity</p>
                </li>
                <li class="tab", data-target="#tab-contributors">
                  <p>Contributors</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

      <!-- similar dreams -->
      <div class="tab-content" id="tab-similar-dreams">
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <div class="likes-avatars">
                  <% if dream.user.has_dream_in?(dream.category) %>
                    <div class="row">
                      <% dreams_in_category_except_this(dream, dream.category).each do |dream| %>
                        <div class="marged-dream-card">
                          <%= render 'shared/dream_card', dream: dream %>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      </div>

      <!-- likes -->
      <div class="tab-content hidden" id="tab-likers">
        <div class="dream-lovers">
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <div class="likes-avatars">
                  <% if @dream.likes.count > 0 %>

                    <% @dream.likes.each do |like| %>
                      <%= link_to dreams_profile_path(like.user) do %>
                        <%= user_avatar_tag like.user, class: 'avatar-medium' %>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- contributors -->
      <div class="tab-content hidden" id="tab-contributors">
        <div class="dream-lovers">
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <div class="likes-avatars">
                  <% if dream.kitty.contributors.count > 0 %>
                    <% dream.kitty.different_user_contributors.each do |contributor| %>
                      <%= link_to dreams_profile_path(contributor) do %>
                        <%= user_avatar_tag contributor, class: 'avatar-medium' %>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>