config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:show, :edit, :update] do
    resource :relationship, only: [:create, :destroy]
    member do
      get '/dreams', to: 'profiles#dreams'
    end
  end

  resources :dreams do
    member do
      put '/realized', to: 'dreams#realized'
    end
    resources :kitties, only: [:show, :new, :create]
    resource :like, only: [:create, :destroy]
  end

  resources :kitties, only: [] do
    put '/reveal', to: 'kitties#reveal'
    resources :contributors, only: [:new, :create]
  end

  resources :contributors, only: [] do
    resources :payments, only: [:new, :create]
  end

  resources :notifications, only: [:show]

  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: :registrations }

  root to: 'pages#home'
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_contributor

  def new
  end

  def create
    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @contributor.price_cents, # or amount_pennies
      description:  "Payment for #{@contributor.kitty.dream.user.first_name}'s dream (#{@contributor.kitty.dream.title}) for contribution #{@contributor.id}",
      currency:     @contributor.price.currency
    )

    @contributor.update(payment: charge.to_json, state: 'paid')

    if !@contributor.private
    @notification = Notification.create!(
        user: @contributor.kitty.dream.user,
        subject: @contributor.kitty.dream,
        content: "<strong>#{@contributor.user.first_name.capitalize} #{@contributor.user.last_name.capitalize}</strong> made a contribution to your dream!")
    end

    redirect_to dream_path(@contributor.kitty.dream)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_contributor_payment_path(@contributor)
  end

  def set_contributor
    @contributor = Contributor.where(state: 'pending').find(params[:contributor_id])
  end
end

app/views/payments/new.html.erb
<div class="container">
  <div class="marged">
    <div class="row">
      <div class="col-xs-12 col-sm-offset-3 col-sm-6">
        <div class="big-card-create-dream">
          <div class="payment-recap">
            <h2>You are about to contribute to the dream:</h2>

            <div class="dream-info">
              <div class="row">
                <div class="center-img">
                  <div class="col-xs-12 col-sm-3">
                    <%= user_avatar_tag @contributor.kitty.dream.user, class: "avatar-square-dreamlist" %>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-9">
                  <h4 class="text-center"><%= @contributor.kitty.dream.title %></h4>
                </div>
              </div>
            </div>


            <%= form_tag contributor_payments_path(@contributor) do %>`
              <article>
                <div class="flex-price">
                  <label class="price">
                    <h4>Your contribution:</h4>
                    <h4><%= humanized_money_with_symbol(@contributor.price) %></h4>
                  </label>
                </div>
              </article>

              <div class="flex-button">
                <div class="new-button">
                 <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>"
                  data-name="My contribution"
                  data-email="<%= current_user.email %>"
                  data-description="Contribution to <%= @contributor.kitty.dream.user.first_name %>'s dream: <%= @contributor.kitty.dream.title%>"
                  data-amount="<%= @contributor.price_cents %>"
                  data-currency="<%= @contributor.price.currency %>"></script>
                  <p class="pay-text-button">Pay now</p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<!-- <script src="https://js.stripe.com/v3/"></script>

<div class="wrapper">
  <div class="marged-stripe">
    <div class="stripe-card">
    <form action="<%= contributor_payments_path(@contributor) %>" method="post" id="payment-form">

      <div class="group">
        <label>
          <span>Name</span>
          <input name="cardholder-name" class="field" placeholder="Jane Doe" />
        </label>
      </div>
      <div class="group">
        <label>
          <span>Card</span>
          <div id="card-element" class="field"></div>
        </label>
      </div>
      <button class='stripe-button' type="submit">Pay $25</button>
      <div class="outcome">
        <div class="card-error" role="alert"></div>
        <div class="success">
          Success! Your Stripe token is <span class="token"></span>
        </div>
      </div>
    </form>
    </div>
  </div>
</div>
 -->